image: python:3.9-slim

pipelines:
  default:
    - step:
        name: Install & Run
        caches:
          - pip
        script:
          # Upgrade pip
          - python -m pip install --upgrade pip
          
          # Install dependencies
          - pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot loguru
          
          # Make sure bgmi is executable
          - chmod +x ./bgmi
          
          # Run Python script
          - python n.py
          
          # Run your binary
          - ./bgmi
